title: 离散数学
description: Discrete Math, 离散数学
theme: just-the-docs

url: https://abotw.github.io/dm

aux_links:
  DM@qzy: https://www.dm2024w.spacepenguin.com.cn/schedule/
  Repo: https://github.com/abotw/dm
